// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0--rc2
// source: api/proto/sync.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeltaSync_GetMissingChunks_FullMethodName = "/sync.DeltaSync/GetMissingChunks"
	DeltaSync_UploadChunks_FullMethodName     = "/sync.DeltaSync/UploadChunks"
	DeltaSync_DownloadFile_FullMethodName     = "/sync.DeltaSync/DownloadFile"
)

// DeltaSyncClient is the client API for DeltaSync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeltaSyncClient interface {
	// client sends a list of hashes; server returns only the ones it DOES NOT have
	GetMissingChunks(ctx context.Context, in *FileSignature, opts ...grpc.CallOption) (*MissingChunksResponse, error)
	// Clinet streams the actual raw bytes of those missing chunks to the server
	UploadChunks(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ChunkPayload, UploadStatus], error)
	// allows a user to request a file for reconstruction
	DownloadFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChunkPayload], error)
}

type deltaSyncClient struct {
	cc grpc.ClientConnInterface
}

func NewDeltaSyncClient(cc grpc.ClientConnInterface) DeltaSyncClient {
	return &deltaSyncClient{cc}
}

func (c *deltaSyncClient) GetMissingChunks(ctx context.Context, in *FileSignature, opts ...grpc.CallOption) (*MissingChunksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MissingChunksResponse)
	err := c.cc.Invoke(ctx, DeltaSync_GetMissingChunks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deltaSyncClient) UploadChunks(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ChunkPayload, UploadStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DeltaSync_ServiceDesc.Streams[0], DeltaSync_UploadChunks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChunkPayload, UploadStatus]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeltaSync_UploadChunksClient = grpc.ClientStreamingClient[ChunkPayload, UploadStatus]

func (c *deltaSyncClient) DownloadFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChunkPayload], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DeltaSync_ServiceDesc.Streams[1], DeltaSync_DownloadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileRequest, ChunkPayload]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeltaSync_DownloadFileClient = grpc.ServerStreamingClient[ChunkPayload]

// DeltaSyncServer is the server API for DeltaSync service.
// All implementations must embed UnimplementedDeltaSyncServer
// for forward compatibility.
type DeltaSyncServer interface {
	// client sends a list of hashes; server returns only the ones it DOES NOT have
	GetMissingChunks(context.Context, *FileSignature) (*MissingChunksResponse, error)
	// Clinet streams the actual raw bytes of those missing chunks to the server
	UploadChunks(grpc.ClientStreamingServer[ChunkPayload, UploadStatus]) error
	// allows a user to request a file for reconstruction
	DownloadFile(*FileRequest, grpc.ServerStreamingServer[ChunkPayload]) error
	mustEmbedUnimplementedDeltaSyncServer()
}

// UnimplementedDeltaSyncServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeltaSyncServer struct{}

func (UnimplementedDeltaSyncServer) GetMissingChunks(context.Context, *FileSignature) (*MissingChunksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMissingChunks not implemented")
}
func (UnimplementedDeltaSyncServer) UploadChunks(grpc.ClientStreamingServer[ChunkPayload, UploadStatus]) error {
	return status.Error(codes.Unimplemented, "method UploadChunks not implemented")
}
func (UnimplementedDeltaSyncServer) DownloadFile(*FileRequest, grpc.ServerStreamingServer[ChunkPayload]) error {
	return status.Error(codes.Unimplemented, "method DownloadFile not implemented")
}
func (UnimplementedDeltaSyncServer) mustEmbedUnimplementedDeltaSyncServer() {}
func (UnimplementedDeltaSyncServer) testEmbeddedByValue()                   {}

// UnsafeDeltaSyncServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeltaSyncServer will
// result in compilation errors.
type UnsafeDeltaSyncServer interface {
	mustEmbedUnimplementedDeltaSyncServer()
}

func RegisterDeltaSyncServer(s grpc.ServiceRegistrar, srv DeltaSyncServer) {
	// If the following call panics, it indicates UnimplementedDeltaSyncServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeltaSync_ServiceDesc, srv)
}

func _DeltaSync_GetMissingChunks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileSignature)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeltaSyncServer).GetMissingChunks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeltaSync_GetMissingChunks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeltaSyncServer).GetMissingChunks(ctx, req.(*FileSignature))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeltaSync_UploadChunks_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DeltaSyncServer).UploadChunks(&grpc.GenericServerStream[ChunkPayload, UploadStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeltaSync_UploadChunksServer = grpc.ClientStreamingServer[ChunkPayload, UploadStatus]

func _DeltaSync_DownloadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeltaSyncServer).DownloadFile(m, &grpc.GenericServerStream[FileRequest, ChunkPayload]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeltaSync_DownloadFileServer = grpc.ServerStreamingServer[ChunkPayload]

// DeltaSync_ServiceDesc is the grpc.ServiceDesc for DeltaSync service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeltaSync_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sync.DeltaSync",
	HandlerType: (*DeltaSyncServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMissingChunks",
			Handler:    _DeltaSync_GetMissingChunks_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadChunks",
			Handler:       _DeltaSync_UploadChunks_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadFile",
			Handler:       _DeltaSync_DownloadFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/sync.proto",
}
