// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc2
// source: api/proto/sync.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	mi := &file_api_proto_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sync_proto_rawDescGZIP(), []int{0}
}

func (x *FileRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type FileSignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	ChunkHashes   []string               `protobuf:"bytes,2,rep,name=chunk_hashes,json=chunkHashes,proto3" json:"chunk_hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileSignature) Reset() {
	*x = FileSignature{}
	mi := &file_api_proto_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSignature) ProtoMessage() {}

func (x *FileSignature) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSignature.ProtoReflect.Descriptor instead.
func (*FileSignature) Descriptor() ([]byte, []int) {
	return file_api_proto_sync_proto_rawDescGZIP(), []int{1}
}

func (x *FileSignature) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileSignature) GetChunkHashes() []string {
	if x != nil {
		return x.ChunkHashes
	}
	return nil
}

type MissingChunksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MissingHashes []string               `protobuf:"bytes,1,rep,name=missing_hashes,json=missingHashes,proto3" json:"missing_hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MissingChunksResponse) Reset() {
	*x = MissingChunksResponse{}
	mi := &file_api_proto_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissingChunksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissingChunksResponse) ProtoMessage() {}

func (x *MissingChunksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissingChunksResponse.ProtoReflect.Descriptor instead.
func (*MissingChunksResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sync_proto_rawDescGZIP(), []int{2}
}

func (x *MissingChunksResponse) GetMissingHashes() []string {
	if x != nil {
		return x.MissingHashes
	}
	return nil
}

type ChunkPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkPayload) Reset() {
	*x = ChunkPayload{}
	mi := &file_api_proto_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkPayload) ProtoMessage() {}

func (x *ChunkPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkPayload.ProtoReflect.Descriptor instead.
func (*ChunkPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_sync_proto_rawDescGZIP(), []int{3}
}

func (x *ChunkPayload) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ChunkPayload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ChunkPayload) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type UploadStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadStatus) Reset() {
	*x = UploadStatus{}
	mi := &file_api_proto_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadStatus) ProtoMessage() {}

func (x *UploadStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadStatus.ProtoReflect.Descriptor instead.
func (*UploadStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_sync_proto_rawDescGZIP(), []int{4}
}

func (x *UploadStatus) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_sync_proto protoreflect.FileDescriptor

const file_api_proto_sync_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/sync.proto\x12\x04sync\"*\n" +
	"\vFileRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\"K\n" +
	"\rFileSignature\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12!\n" +
	"\fchunk_hashes\x18\x02 \x03(\tR\vchunkHashes\">\n" +
	"\x15MissingChunksResponse\x12%\n" +
	"\x0emissing_hashes\x18\x01 \x03(\tR\rmissingHashes\"J\n" +
	"\fChunkPayload\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"B\n" +
	"\fUploadStatus\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xc4\x01\n" +
	"\tDeltaSync\x12D\n" +
	"\x10GetMissingChunks\x12\x13.sync.FileSignature\x1a\x1b.sync.MissingChunksResponse\x128\n" +
	"\fUploadChunks\x12\x12.sync.ChunkPayload\x1a\x12.sync.UploadStatus(\x01\x127\n" +
	"\fDownloadFile\x12\x11.sync.FileRequest\x1a\x12.sync.ChunkPayload0\x01B\x16Z\x14delta-sync-pb/pkg/pbb\x06proto3"

var (
	file_api_proto_sync_proto_rawDescOnce sync.Once
	file_api_proto_sync_proto_rawDescData []byte
)

func file_api_proto_sync_proto_rawDescGZIP() []byte {
	file_api_proto_sync_proto_rawDescOnce.Do(func() {
		file_api_proto_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_sync_proto_rawDesc), len(file_api_proto_sync_proto_rawDesc)))
	})
	return file_api_proto_sync_proto_rawDescData
}

var file_api_proto_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_sync_proto_goTypes = []any{
	(*FileRequest)(nil),           // 0: sync.FileRequest
	(*FileSignature)(nil),         // 1: sync.FileSignature
	(*MissingChunksResponse)(nil), // 2: sync.MissingChunksResponse
	(*ChunkPayload)(nil),          // 3: sync.ChunkPayload
	(*UploadStatus)(nil),          // 4: sync.UploadStatus
}
var file_api_proto_sync_proto_depIdxs = []int32{
	1, // 0: sync.DeltaSync.GetMissingChunks:input_type -> sync.FileSignature
	3, // 1: sync.DeltaSync.UploadChunks:input_type -> sync.ChunkPayload
	0, // 2: sync.DeltaSync.DownloadFile:input_type -> sync.FileRequest
	2, // 3: sync.DeltaSync.GetMissingChunks:output_type -> sync.MissingChunksResponse
	4, // 4: sync.DeltaSync.UploadChunks:output_type -> sync.UploadStatus
	3, // 5: sync.DeltaSync.DownloadFile:output_type -> sync.ChunkPayload
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_sync_proto_init() }
func file_api_proto_sync_proto_init() {
	if File_api_proto_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_sync_proto_rawDesc), len(file_api_proto_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_sync_proto_goTypes,
		DependencyIndexes: file_api_proto_sync_proto_depIdxs,
		MessageInfos:      file_api_proto_sync_proto_msgTypes,
	}.Build()
	File_api_proto_sync_proto = out.File
	file_api_proto_sync_proto_goTypes = nil
	file_api_proto_sync_proto_depIdxs = nil
}
